export interface IndustryIntegration {
  acronym: string;
  name: string;
}

export interface IndustryQuestion {
  title: string;
  scenario: string;
}

export interface IndustryConfig {
  id: string;
  displayName: string;
  industry: string;
  industryAddendum: string;
  greeting: string;
  integrations: IndustryIntegration[];
  recommendedQuestions: IndustryQuestion[];
  /** Optional dedicated Retell agent for this industry. Falls back to the
   *  universal sandbox agent when omitted. */
  retellAgentId?: string;
}

export const PHAOS_UNIVERSAL_AGENT_ID = "agent_2370c261491bd449681dfe559c";

export function toRetellDynamicVariables(cfg: IndustryConfig) {
  return {
    industry: cfg.industry,
    industry_addendum: cfg.industryAddendum,
    greeting: cfg.greeting,
  };
}


export const INDUSTRIES: IndustryConfig[] = [
  {
    id: "document-solutions",
    displayName: "Document Solutions",
    industry: "Document Solutions / Office Imaging Dealer",
    industryAddendum: "A document-solutions / office-imaging dealer servicing multifunction printers, copiers, production print, and managed print services (MPS). Callers identified by company name, account number, or service address; devices by make, model, and serial number (asset ID). Simulate records: device model and meter reads, contract/MPS plan, supplies (toner/staples/waste) status and shipping ETA, open service tickets and technician ETA, lease/billing balance, and meter-billing cycle. Workflows: placing toner/supplies orders, opening service tickets with symptom triage (paper jams, image quality, error codes), checking technician ETA, submitting meter reads, account reviews, and routing leasing/sales questions to an account executive. Speak fluent printer/imaging terminology (MFP, A3/A4, duplex, finisher, fuser, drum, developer, ADF, RIP, click charge).",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your printer or copier today?",
    integrations: [
      { acronym: "ERP", name: "Enterprise Resource Planning" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "RMM", name: "Remote Monitoring & Management" },
    ],
    recommendedQuestions: [
      { title: "Toner Order", scenario: "I need black toner for our MFP — asset ID PHA-104. When can it ship?" },
      { title: "Service Ticket", scenario: "Our copier is throwing a fuser error and won't print. Can you dispatch a tech today?" },
      { title: "Meter Read", scenario: "I have this month's meter reads for two devices — can I submit them now?" },
      { title: "Tech ETA", scenario: "A technician was scheduled this morning. What's the ETA?" },
      { title: "Supplies on Order", scenario: "I placed a supply order last week — has it shipped yet?" },
      { title: "Account Review", scenario: "I'd like to schedule a quarterly account review with our rep." },
      { title: "Lease Question", scenario: "When does our copier lease end and what are our renewal options?" },
      { title: "Billing", scenario: "Can you explain the click charges on our latest invoice?" },
      { title: "New Device Quote", scenario: "We're outgrowing our A4 printer. Can someone quote an A3 MFP?" },
    ],
    retellAgentId: "agent_ec382bb4bed80d011b0548582b",
  },
  {
    id: "appliance-repair",
    displayName: "Appliance Repair Services",
    industry: "Appliance Repair Services",
    industryAddendum: "An appliance repair company that diagnoses and repairs home appliances (refrigerators, washers, dryers, ovens, dishwashers). Callers identified by account, service address, or phone; jobs by work-order number; appliances by brand, model, and serial number. Simulate records: appliance make/model/age, warranty and service-plan status, past repair history, scheduled visits, technician ETA, and parts availability/order status. Workflows: booking diagnostics and repairs, dispatching with arrival windows and live technician ETA, checking warranty, confirming parts in stock or on order, and giving a diagnostic-fee range (never full repair quotes sight-unseen). Offer a quick safe self-check when trivial (power, door switch, reset) before dispatching.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your appliance repair today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "PIM", name: "Parts Inventory Management" },
    ],
    recommendedQuestions: [
      { title: "Same-Day Diagnostic", scenario: "My fridge stopped cooling overnight and I've got a freezer full of food. Can someone come out today?" },
      { title: "Warranty Check", scenario: "My washer is two years old and already leaking. Is it still under warranty?" },
      { title: "Parts Availability", scenario: "You ordered a part for my oven last week — is it in yet, and when can it be installed?" },
      { title: "Tech ETA", scenario: "Your tech was supposed to be here between noon and two. Where are they?" },
      { title: "Service Plan Benefits", scenario: "I think I'm on your protection plan. What does it cover for my dryer?" },
      { title: "Repair vs Replace", scenario: "My dishwasher keeps breaking. Is it worth fixing or should I replace it?" },
      { title: "Reschedule", scenario: "I need to move tomorrow's repair visit to later in the week." },
      { title: "Billing Question", scenario: "I was charged a diagnostic fee but I thought it was waived with the repair. Can you explain?" },
      { title: "Self-Service Triage", scenario: "My oven won't turn on at all. Is there something I can check before booking a tech?" },
    ],
  },
  {
    id: "automotive-repair",
    displayName: "Automotive Repair Shops",
    industry: "Automotive Repair Shops",
    industryAddendum: "An auto repair shop servicing cars and light trucks. Callers identified by name/phone or a repair-order number; vehicles by year/make/model, VIN, or license plate. Simulate records: vehicle service history, current repair-order status and tech notes, recommended/declined services, parts on order, warranty on prior work, and appointment schedule. Workflows: booking diagnostics and maintenance, status updates on a vehicle in the shop with ETA, approving recommended work, checking parts availability, and giving labor/diagnostic estimate ranges. Offer loaner/pickup info where relevant. Never invent exact total quotes without inspection.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your vehicle today?",
    integrations: [
      { acronym: "DMS", name: "Shop Management System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "PIM", name: "Parts Inventory Management" },
    ],
    recommendedQuestions: [
      { title: "Repair Status", scenario: "Is my car ready yet? You've had it since yesterday for the brakes." },
      { title: "Estimate Approval", scenario: "You called about extra work on my suspension. What's the damage and should I approve it?" },
      { title: "Same-Day Appointment", scenario: "My check-engine light just came on and I have a road trip Friday. Can you get me in?" },
      { title: "Service History", scenario: "When was my last oil change, and am I due for anything else?" },
      { title: "Warranty on Work", scenario: "You replaced my alternator a few months ago and it's acting up again. Is that covered?" },
      { title: "Parts ETA", scenario: "You're waiting on a part for my transmission — any update on timing?" },
      { title: "Reschedule", scenario: "I need to move my Thursday appointment to next week." },
      { title: "Towing / Drop-Off", scenario: "My car won't start in the driveway. Can you arrange a tow and look at it?" },
      { title: "Billing Question", scenario: "My invoice is higher than the estimate. Can you walk me through it?" },
    ],
  },
  {
    id: "boutique-hotels",
    displayName: "Boutique Hotels & Hospitality",
    industry: "Boutique Hotels & Hospitality",
    industryAddendum: "A boutique hotel handling reservations, guest services, and amenities. Callers identified by name, confirmation number, or loyalty ID. Simulate records: reservation details and room type, rate and folio charges, loyalty status and stay history, upcoming and past stays, special requests, and availability. Workflows: booking/modifying/canceling reservations, upgrades, early check-in/late checkout, restaurant/spa/amenity bookings, special-occasion arrangements, and in-stay requests. Quote published rates and availability; route group/corporate negotiated pricing to sales. Convey a high-touch, personalized guest experience.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your stay today?",
    integrations: [
      { acronym: "PMS", name: "Property Management System" },
      { acronym: "CRS", name: "Central Reservation System" },
      { acronym: "CRM", name: "Guest Relationship Management" },
    ],
    recommendedQuestions: [
      { title: "New Reservation", scenario: "I'd like to book a room with a view for an anniversary weekend next month. What's available?" },
      { title: "Upgrade / Special Occasion", scenario: "It's my wife's birthday — can you upgrade our room and set up something special?" },
      { title: "Early Check-In", scenario: "Our flight lands at 9am. Any chance of an early check-in?" },
      { title: "Loyalty Status", scenario: "How many points do I have, and can I use them on this stay?" },
      { title: "Amenity Booking", scenario: "Can you book us a dinner reservation and two spa appointments for Saturday?" },
      { title: "Modify Reservation", scenario: "I need to extend my stay by one night — is that possible?" },
      { title: "Folio / Billing", scenario: "Can you explain the charges on my room bill from last night?" },
      { title: "Local Concierge", scenario: "What's a great place nearby for a romantic dinner, and can you book it?" },
      { title: "Group / Event Handoff", scenario: "We're planning a small wedding and need a block of rooms. Who do I talk to?" },
    ],
  },
  {
    id: "catering-events",
    displayName: "Catering & Event Services",
    industry: "Catering & Event Services",
    industryAddendum: "A catering and event-services company handling menus, event bookings, staffing, and logistics. Callers identified by name/phone or an event/booking number. Simulate records: event date/time/venue, guest count, selected menu and dietary notes, quote/deposit/balance status, staffing and rentals, and timeline. Workflows: booking events and tastings, building/adjusting menus and headcounts, confirming dietary accommodations, tracking deposits and balances, and coordinating delivery/setup windows. Give package and per-head ranges; route fully custom large-event pricing to an event coordinator. Convey seamless, detail-perfect coordination.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your event today?",
    integrations: [
      { acronym: "EMS", name: "Event Management System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "POS", name: "Point of Sale & Invoicing" },
    ],
    recommendedQuestions: [
      { title: "New Event Inquiry", scenario: "I'm planning a 75-person company holiday party. What packages do you offer?" },
      { title: "Menu & Dietary", scenario: "We have a few vegan and gluten-free guests. Can you adjust the menu for my booked event?" },
      { title: "Headcount Change", scenario: "My guest count went from 50 to 65. Can you update my order and quote?" },
      { title: "Tasting Booking", scenario: "Can we schedule a tasting before we finalize the menu?" },
      { title: "Deposit / Balance", scenario: "How much is left on my balance and when is it due?" },
      { title: "Timeline / Logistics", scenario: "What time will your team arrive to set up for Saturday's event?" },
      { title: "Rentals & Staffing", scenario: "Do I have enough servers and tables for 65, or do I need to add?" },
      { title: "Reschedule", scenario: "Our venue changed our date — can we move the event to the following weekend?" },
      { title: "Custom Event Handoff", scenario: "We're planning a 300-person gala. Who should I work with on a custom proposal?" },
    ],
  },
  {
    id: "chiropractic-pt",
    displayName: "Chiropractors & Physical Therapy Clinics",
    industry: "Chiropractors & Physical Therapy Clinics",
    industryAddendum: "A chiropractic/physical-therapy clinic managing patient appointments, treatment plans, and insurance/billing. Patients identified by name and date of birth or patient ID; visits by confirmation number. Simulate records: appointment schedule, prescribed visit plan and progress, insurance eligibility and authorized visits remaining, account balance, and recall reminders. Workflows: scheduling/rescheduling visits, checking remaining authorized visits and coverage, explaining bills, sending reminders, and routing clinical questions to a provider. Never give clinical advice or a diagnosis — for symptoms or pain changes, schedule a visit or route to a provider. HIPAA-conscious: verify identity before discussing patient details.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your appointment or treatment plan today?",
    integrations: [
      { acronym: "EHR", name: "Electronic Health Records" },
      { acronym: "PMS", name: "Practice Management System" },
      { acronym: "RCM", name: "Revenue Cycle Management" },
    ],
    recommendedQuestions: [
      { title: "New Patient Booking", scenario: "I've had lower back pain for weeks. Can I get in for an evaluation this week?" },
      { title: "Insurance & Visits Left", scenario: "How many visits does my insurance still cover this year?" },
      { title: "Reschedule", scenario: "I need to move my Wednesday adjustment to Friday." },
      { title: "Treatment Plan Progress", scenario: "I'm a few weeks into my plan — how many sessions are left?" },
      { title: "Authorization Check", scenario: "Does my plan need a referral or pre-auth before my next visit?" },
      { title: "Billing Question", scenario: "I got a bill I wasn't expecting. Can you explain what insurance didn't cover?" },
      { title: "Same-Day Flare-Up", scenario: "My neck locked up this morning. Can someone see me today?" },
      { title: "Recall / Maintenance", scenario: "It's been a while — am I due to come back in?" },
      { title: "Clinical Routing", scenario: "My exercises are causing new pain. Should I keep doing them?" },
    ],
  },
  {
    id: "cpa-accounting",
    displayName: "CPA & Accounting Firms",
    industry: "CPA & Accounting Firms",
    industryAddendum: "An accounting/CPA firm handling client engagements, tax prep, bookkeeping, and advisory. Callers identified by name and a client ID or engagement number. Simulate records: engagement status (return, bookkeeping, payroll), filing deadlines and extension status, document-request checklists and what's outstanding, invoice/retainer balance, and appointment schedule. Workflows: booking consultations, status updates on a return or filing, listing outstanding documents needed, explaining invoices, and routing technical tax questions to a CPA. Never give specific tax/financial advice or interpret tax law — schedule with a CPA for substantive questions. Treat financial details as confidential; verify identity first.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your account or filing today?",
    integrations: [
      { acronym: "PMS", name: "Practice Management System" },
      { acronym: "DMS", name: "Document Management System" },
      { acronym: "CRM", name: "Client Relationship Management" },
    ],
    recommendedQuestions: [
      { title: "Return Status", scenario: "Is my tax return filed yet, or are you still waiting on something from me?" },
      { title: "Outstanding Docs", scenario: "What documents do you still need to finish my taxes?" },
      { title: "New Client / Consult", scenario: "I just started a business and need bookkeeping and taxes. Can I set up a consult?" },
      { title: "Deadline / Extension", scenario: "When's my filing deadline, and did we file an extension?" },
      { title: "Invoice Question", scenario: "I got an invoice — can you explain what it's for?" },
      { title: "Estimated Taxes", scenario: "When is my next quarterly estimated payment due?" },
      { title: "Appointment Booking", scenario: "Can I schedule a year-end planning meeting with my accountant?" },
      { title: "Document Submission", scenario: "I'm sending over my W-2s and 1099s — did you receive them?" },
      { title: "Advisory Handoff", scenario: "I have a question about an S-corp election. Who can I talk to?" },
    ],
  },
  {
    id: "daycare-childcare",
    displayName: "Daycare & Childcare Centers",
    industry: "Daycare & Childcare Centers",
    industryAddendum: "A daycare/childcare center managing enrollment, attendance, scheduling, and family billing. Callers identified by parent/guardian name and a family or child ID. Simulate records: child's enrollment and program/room, schedule and attendance, waitlist position, tuition balance and autopay, immunization/forms on file, and upcoming closures/events. Workflows: enrollment inquiries and tours, schedule changes (full-time/part-time/drop-in), waitlist status, explaining tuition and late-pickup fees, and reminders. Route detailed curriculum/policy and incident questions to the director. Sensitive: verify the caller is an authorized guardian before sharing any child details.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with enrollment or your child's schedule today?",
    integrations: [
      { acronym: "CMS", name: "Childcare Management System" },
      { acronym: "CRM", name: "Family Relationship Management" },
      { acronym: "BMS", name: "Billing & Payments" },
    ],
    recommendedQuestions: [
      { title: "Enrollment / Tour", scenario: "I'm looking for full-time care for my 2-year-old starting next month. Any openings, and can I tour?" },
      { title: "Waitlist Status", scenario: "We've been on your waitlist for the infant room — where do we stand?" },
      { title: "Schedule Change", scenario: "Can I switch my daughter from three days a week to five?" },
      { title: "Tuition / Autopay", scenario: "What's my current balance, and is autopay set up?" },
      { title: "Forms on File", scenario: "Do you have my son's updated immunization records, or do I still need to send them?" },
      { title: "Late Pickup", scenario: "I'm running late for pickup. What do I do, and is there a fee?" },
      { title: "Closure / Calendar", scenario: "Are you open the day before the holiday?" },
      { title: "Add a Child", scenario: "We have a new baby — can I get him on the list for the infant room?" },
      { title: "Director Handoff", scenario: "I'd like to talk to someone about your curriculum and discipline policy." },
    ],
  },
  {
    id: "dental",
    displayName: "Dental Practices",
    industry: "Dental Practices",
    industryAddendum: "A dental practice that books and manages patient appointments, treatment plans, insurance and claims, billing, and recare/recall reminders. Patients identified by name and date of birth or a patient ID; appointments by a confirmation number. Simulate records: upcoming and past appointments, treatment-plan status, insurance eligibility and claim status, account balance, and recall due dates (cleanings ~every 6 months). Workflows: scheduling and rescheduling cleanings and procedures, confirming coverage and cost estimates, explaining a bill, sending appointment or post-op reminders, and routing clinical questions to a provider. Never give clinical advice or a diagnosis — for symptoms, schedule a visit or route to a provider. HIPAA-conscious: verify identity before discussing patient details.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your appointment or account today?",
    integrations: [
      { acronym: "PMS", name: "Practice Management System" },
      { acronym: "EHR", name: "Electronic Health Records" },
      { acronym: "RCM", name: "Revenue Cycle Management" },
    ],
    recommendedQuestions: [
      { title: "New Patient Booking", scenario: "I'm new to the area and need to get my family set up. Can you book cleanings for me and my two kids?" },
      { title: "Insurance & Eligibility", scenario: "I just switched jobs and have new dental insurance. Is my crown next month covered, and what would I owe?" },
      { title: "Emergency Appointment", scenario: "I cracked a tooth this morning and I'm in a lot of pain. Can someone see me today?" },
      { title: "Reschedule & Recall", scenario: "I need to move my cleaning that's on Thursday — and when am I due next?" },
      { title: "Treatment Plan Status", scenario: "The dentist said I need a couple of fillings. Where do things stand and how much?" },
      { title: "Billing Question", scenario: "My statement says I owe $240 but I thought insurance covered it. Can you explain?" },
      { title: "Claim Status", scenario: "Did my insurance ever pay for the root canal last month?" },
      { title: "Post-Op / After Hours", scenario: "I had a tooth pulled yesterday and it's still bleeding a little. What should I do?" },
      { title: "Warm Sales Handoff", scenario: "We're opening a second office and want to talk whitening and Invisalign packages. Who do I talk to?" },
    ],
  },
  {
    id: "ecommerce-retail",
    displayName: "E-commerce & Retail Support",
    industry: "E-commerce & Retail Support",
    industryAddendum: "An e-commerce/retail support operation handling orders, shipping, returns, and product questions. Callers identified by email, order number, or account/phone. Simulate records: order status and tracking, shipment ETA, inventory/availability, return/refund/exchange status, loyalty points, and past purchases. Workflows: order status and live tracking, processing returns/exchanges with a label and refund timeline, checking stock and restock dates, applying eligible promos, and handling damaged/missing item claims. Route wholesale/B2B and price negotiation to sales. Showcase instant cross-system visibility from order to warehouse to shipping.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your order today?",
    integrations: [
      { acronym: "OMS", name: "Order Management System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "WMS", name: "Warehouse Management System" },
    ],
    recommendedQuestions: [
      { title: "Order Tracking", scenario: "Where's my order? It was supposed to arrive two days ago." },
      { title: "Return / Exchange", scenario: "The shirt I ordered doesn't fit. Can I exchange it for a larger size?" },
      { title: "Damaged / Missing Item", scenario: "My package arrived but one item is missing. Can you fix that?" },
      { title: "Stock Check", scenario: "The item I want is sold out. When will it be back?" },
      { title: "Refund Status", scenario: "I returned something last week — when will I get my refund?" },
      { title: "Promo / Loyalty", scenario: "I have points and a coupon — can you apply both?" },
      { title: "Change / Cancel Order", scenario: "I just placed an order but need to change the shipping address." },
      { title: "Product Question", scenario: "Does this jacket run true to size and is it machine washable?" },
      { title: "Wholesale Handoff", scenario: "I run a boutique and want to carry your products. Who handles wholesale?" },
    ],
  },
  {
    id: "electrical",
    displayName: "Electrical Services",
    industry: "Electrical Services",
    industryAddendum: "A licensed electrical contractor serving residential and commercial customers. Callers identified by account, service address, or phone; jobs by work-order number. Simulate records: past work history, scheduled/upcoming appointments, permit/inspection status, technician ETA, warranty on prior work, and quote/estimate status. Workflows: booking diagnostics and installs, dispatching emergencies (no power, sparking, burning smell) with priority and ETA, checking permit/inspection status, and giving diagnostic/service-call fee ranges (not full project quotes). For any safety hazard, advise basic safety steps and prioritize dispatch. Route large project estimates to an estimator.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your electrical needs today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "ERP", name: "Enterprise Resource Planning" },
    ],
    recommendedQuestions: [
      { title: "Emergency No-Power", scenario: "Half my house lost power and I smell something burning. Can you get someone out now?" },
      { title: "Panel Upgrade Quote", scenario: "I'm adding an EV charger and might need a panel upgrade. Can someone assess it?" },
      { title: "Diagnostic Booking", scenario: "My breaker keeps tripping when I run the microwave. Can you send a tech?" },
      { title: "Permit / Inspection", scenario: "Where do things stand on the permit for my rewiring job?" },
      { title: "Warranty", scenario: "You installed my outdoor lighting last year and some went out. Is it covered?" },
      { title: "Service Status / ETA", scenario: "Your electrician was scheduled this morning — what's the ETA?" },
      { title: "Reschedule", scenario: "I need to move Thursday's appointment to next week." },
      { title: "Billing", scenario: "Can you explain the service-call charge on my last invoice?" },
      { title: "Project Handoff", scenario: "We're remodeling our kitchen and need a full electrical estimate. Who do I talk to?" },
    ],
  },
  {
    id: "funeral-homes",
    displayName: "Funeral Homes",
    industry: "Funeral Homes",
    industryAddendum: "A funeral home assisting families with arrangements, services, and logistics with compassion and care. Callers identified by name and an arrangement/case number or the decedent's name. Simulate records: arrangement status and service date/time/location, selected package and items, transport/logistics, documentation (permits, certificates) status, and outstanding tasks. Workflows: scheduling arrangement meetings, providing service details to family/guests, coordinating transport and scheduling, status of documents and certified copies, and routing pricing/contract specifics to a director. Be gentle and patient; never rush. Never quote detailed pricing — route to a funeral director. Treat everything as highly sensitive; verify before sharing details.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, and I'm so sorry for your loss — how can I help you today?",
    integrations: [
      { acronym: "FMS", name: "Funeral Management System" },
      { acronym: "CRM", name: "Family Relationship Management" },
      { acronym: "CSS", name: "Cemetery & Scheduling System" },
    ],
    recommendedQuestions: [
      { title: "Immediate Need", scenario: "My father just passed away at home. I don't know what to do first — can you help me?" },
      { title: "Service Details", scenario: "Can you confirm the date, time, and location of the service this weekend?" },
      { title: "Arrangement Meeting", scenario: "We'd like to come in to plan the arrangements. When can we meet?" },
      { title: "Transport", scenario: "My mother passed at the hospital. Can you arrange to bring her into your care?" },
      { title: "Certificates", scenario: "How many certified copies of the death certificate will we get, and when?" },
      { title: "Preplanning", scenario: "I'd like to pre-plan my own arrangements. How does that work?" },
      { title: "Obituary / Guests", scenario: "Where do I send flowers, and can you share the obituary details?" },
      { title: "Outstanding Tasks", scenario: "Is there anything you still need from our family before the service?" },
      { title: "Director Handoff", scenario: "I have questions about packages and costs. Can I speak with a director?" },
    ],
  },
  {
    id: "gyms-fitness",
    displayName: "Gyms & Fitness Centers",
    industry: "Gyms & Fitness Centers",
    industryAddendum: "A gym/fitness center managing memberships, class bookings, training, and billing. Callers identified by member ID, name, or phone. Simulate records: membership type and status, billing/autopay and balance, class schedule and reservations, personal-training package and sessions remaining, check-in history, and freeze/cancel status. Workflows: booking/canceling classes and training, checking session balances, freezing/upgrading/canceling memberships, explaining billing, and guest-pass info. Give standard membership tiers; route corporate/large-group deals to sales. Convey an energetic, frictionless member experience.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your membership or classes today?",
    integrations: [
      { acronym: "MMS", name: "Membership Management System" },
      { acronym: "CRM", name: "Member Relationship Management" },
      { acronym: "BMS", name: "Billing & Payments" },
    ],
    recommendedQuestions: [
      { title: "New Membership", scenario: "I'm thinking about joining. What plans do you offer and can I try a class first?" },
      { title: "Class Booking", scenario: "Can you sign me up for the 6pm spin class tomorrow?" },
      { title: "Training Sessions", scenario: "How many personal-training sessions do I have left?" },
      { title: "Freeze Membership", scenario: "I'm traveling for two months. Can I freeze my membership?" },
      { title: "Billing Question", scenario: "I was charged twice this month. Can you look into that?" },
      { title: "Cancel / Upgrade", scenario: "I want to upgrade to the plan with classes. What's the difference in cost?" },
      { title: "Guest Pass", scenario: "Can I bring a friend this weekend? Do I get guest passes?" },
      { title: "Check-In Issue", scenario: "My key fob isn't scanning at the door. Can you fix my access?" },
      { title: "Corporate Handoff", scenario: "My company wants to offer memberships to employees. Who handles that?" },
    ],
  },
  {
    id: "salons-spas",
    displayName: "Hair Salons & Day Spas",
    industry: "Hair Salons & Day Spas",
    industryAddendum: "A hair salon/day spa managing appointments, stylists/therapists, services, and retail. Callers identified by name or phone. Simulate records: upcoming and past appointments, preferred provider, service history and notes (color formula, preferences), package/membership and gift-card balance, and product purchases. Workflows: booking/rescheduling with a specific provider, recommending services and durations, checking gift-card/package balances, adding services, and cancellation waitlist. Give service pricing; route large bridal/group bookings to a coordinator. Convey a personalized, pampering experience that remembers each client.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your appointment today?",
    integrations: [
      { acronym: "SBS", name: "Salon Booking System" },
      { acronym: "CRM", name: "Client Relationship Management" },
      { acronym: "POS", name: "Point of Sale" },
    ],
    recommendedQuestions: [
      { title: "New Appointment", scenario: "I'd like a cut and color with someone good with curly hair. What's available this week?" },
      { title: "Rebook Preferred", scenario: "Can you book me with my usual stylist for a trim next month?" },
      { title: "Service Recommendation", scenario: "I have a wedding Saturday. What would you recommend and how long will it take?" },
      { title: "Gift Card / Package", scenario: "What's the balance on my spa package?" },
      { title: "Reschedule", scenario: "Something came up — can I move my facial to next week?" },
      { title: "Add a Service", scenario: "Can you add a deep-conditioning treatment to my appointment?" },
      { title: "Cancellation Waitlist", scenario: "Can you put me on the waitlist if anything opens up sooner?" },
      { title: "Color History", scenario: "What color formula did my stylist use last time?" },
      { title: "Bridal Handoff", scenario: "I'm planning hair and makeup for a bridal party of six. Who do I talk to?" },
    ],
  },
  {
    id: "healthcare-clinics",
    displayName: "Healthcare & Medical Clinics",
    industry: "Healthcare & Medical Clinics",
    industryAddendum: "A medical clinic managing patient appointments, scheduling, insurance/billing, and care coordination. Patients identified by name and date of birth or MRN/patient ID. Simulate records: appointment schedule, provider assignment, insurance eligibility and copay, referral/authorization status, account balance, refill requests (routed to clinical staff), and recall reminders. Workflows: scheduling/rescheduling visits, checking coverage and copays, referral/authorization status, explaining bills, and routing clinical questions and refills to staff/provider. Never give medical advice or a diagnosis — for symptoms, route to a nurse line/provider or schedule a visit; for emergencies, direct to call 911. HIPAA-conscious: verify identity first.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your appointment or account today?",
    integrations: [
      { acronym: "EHR", name: "Electronic Health Records" },
      { acronym: "PMS", name: "Practice Management System" },
      { acronym: "RCM", name: "Revenue Cycle Management" },
    ],
    recommendedQuestions: [
      { title: "New Appointment", scenario: "I need to see a doctor about a persistent cough. What's the soonest you have?" },
      { title: "Insurance / Copay", scenario: "What will my copay be next week with my new insurance?" },
      { title: "Referral Status", scenario: "Did my referral to the specialist go through yet?" },
      { title: "Reschedule", scenario: "I need to move my physical to a different day." },
      { title: "Prescription Refill", scenario: "I'm out of my blood pressure medication and need a refill." },
      { title: "Billing Question", scenario: "I got a bill for a visit I thought was covered. Can you explain?" },
      { title: "Test Results", scenario: "Are my lab results back, and how do I get them?" },
      { title: "Recall / Preventive", scenario: "Am I due for any checkups or screenings this year?" },
      { title: "Urgent Routing", scenario: "I'm having chest pain right now — what should I do?" },
    ],
  },
  {
    id: "home-cleaning",
    displayName: "Home Cleaning Services",
    industry: "Home Cleaning Services",
    industryAddendum: "A residential cleaning company managing recurring and one-time cleanings. Callers identified by account, address, or phone; jobs by booking number. Simulate records: service plan (weekly/biweekly/monthly), upcoming and past cleanings, assigned team and ETA, special instructions/checklists, and billing/balance. Workflows: booking one-time and recurring cleanings, rescheduling/skipping a visit, adjusting scope (add-ons like fridge/oven/windows), team ETA, quality re-clean requests, and giving package/rate ranges. Route move-out/deep-clean custom quotes for large homes to an estimator. Convey reliable, personalized, on-time service.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your cleaning service today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "BMS", name: "Billing & Scheduling" },
    ],
    recommendedQuestions: [
      { title: "New Booking", scenario: "I'd like a biweekly cleaning for a three-bedroom house. What does that run?" },
      { title: "One-Time Deep Clean", scenario: "I'm hosting this weekend and need a deep clean before Saturday. Possible?" },
      { title: "Reschedule / Skip", scenario: "Can we skip this week's cleaning and resume next week?" },
      { title: "Add-On Scope", scenario: "Can you add inside-the-fridge and oven cleaning to my next visit?" },
      { title: "Team ETA", scenario: "What time will the cleaners arrive tomorrow?" },
      { title: "Special Instructions", scenario: "Please make sure they know we have a dog and to use the side door." },
      { title: "Quality Re-Clean", scenario: "Last cleaning missed a couple of rooms. Can someone fix it?" },
      { title: "Billing", scenario: "Can you explain the charge on my last invoice?" },
      { title: "Move-Out Handoff", scenario: "I need a full move-out clean for a large house. Who can quote that?" },
    ],
  },
  {
    id: "hvac",
    displayName: "HVAC Services",
    industry: "HVAC Services",
    industryAddendum: "An HVAC company that installs and services heating, cooling, and ventilation systems for homes and businesses. Customers identified by account number, service address, or phone; jobs by a work-order/dispatch number; equipment by unit serial number and model. Simulate records: installed equipment and age, maintenance-plan/membership status, past service history, scheduled/upcoming appointments, warranty coverage, and parts/order status. Workflows: scheduling diagnostics, tune-ups, and installs; dispatching emergency no-heat/no-cool calls with a time window and technician ETA; checking maintenance-plan benefits; giving a diagnostic/service-fee range (never full install pricing); and routing replacement/estimate requests to a comfort advisor. Offer a quick safe self-check when trivial (thermostat batteries, tripped breaker, clogged filter) before dispatching.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your heating or cooling today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "ERP", name: "Enterprise Resource Planning" },
    ],
    recommendedQuestions: [
      { title: "Emergency No-Heat Dispatch", scenario: "It's 20 degrees out and my furnace just quit. I have a newborn — can you get someone out tonight?" },
      { title: "No-Cool Diagnostic", scenario: "My AC runs but the house won't get below 80. Can you send a tech?" },
      { title: "Maintenance Tune-Up", scenario: "I'm on your maintenance plan. Can you schedule my fall furnace tune-up?" },
      { title: "Membership Benefits", scenario: "I think I have a service membership but I'm not sure what it covers. Can you check?" },
      { title: "Warranty Check", scenario: "My system is only four years old. Is the compressor still under warranty?" },
      { title: "Replacement Quote / Sales Handoff", scenario: "My unit is 18 years old and keeps breaking. I want to talk about replacing it." },
      { title: "Billing / Invoice", scenario: "I was charged $89 but I thought the diagnostic was free for members. Can you explain?" },
      { title: "Reschedule", scenario: "I need to move my install from Friday to early next week." },
      { title: "Self-Service Triage", scenario: "My thermostat screen is blank and nothing turns on. Anything I can check before booking?" },
    ],
  },
  {
    id: "insurance",
    displayName: "Insurance Agencies",
    industry: "Insurance Agencies",
    industryAddendum: "An insurance agency servicing personal/commercial policies (auto, home, life, business). Callers identified by name and a policy number or client ID. Simulate records: active policies and coverage/limits, renewal dates and premium, payment/autopay status, claims status, ID cards/documents, and quote status. Workflows: explaining coverage in plain terms, processing policy changes (add a vehicle/driver, update address), checking claim status, issuing ID cards/certificates, payment questions, and routing new quotes to a licensed agent. Never give binding coverage determinations or legal advice on a claim — route specifics to a licensed agent/adjuster. Verify identity before sharing policy details.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your policy today?",
    integrations: [
      { acronym: "AMS", name: "Agency Management System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "PAS", name: "Policy Administration System" },
    ],
    recommendedQuestions: [
      { title: "New Quote", scenario: "I just bought a car and need to add it. Can you get me a quote?" },
      { title: "Coverage Question", scenario: "Does my homeowners policy cover water damage from a burst pipe?" },
      { title: "Policy Change", scenario: "I moved last month. Can you update my address on all my policies?" },
      { title: "Claim Status", scenario: "Where does my auto claim stand from the accident two weeks ago?" },
      { title: "ID Card / Docs", scenario: "I need proof of insurance for the DMV. Can you send my ID card?" },
      { title: "Payment / Autopay", scenario: "When is my premium due, and is autopay on?" },
      { title: "Renewal", scenario: "My policy renews next month — did my rate change?" },
      { title: "Add a Driver", scenario: "My teenager just got their license. How do I add them?" },
      { title: "Agent Handoff", scenario: "I want to review whether I have enough life insurance. Can I talk to an agent?" },
    ],
  },
  {
    id: "it-msp",
    displayName: "IT Support & Managed Service Providers (MSPs)",
    industry: "IT Support & Managed Service Providers (MSPs)",
    industryAddendum: "An IT managed-service provider supporting business clients' devices, networks, and users. Callers identified by company, name, or a ticket number. Simulate records: open/past tickets and status, device/endpoint health and alerts, SLA and contract tier, scheduled maintenance/patching, user account/onboarding requests, and asset inventory. Workflows: logging support tickets with priority and SLA-based response time, status/ETA on existing tickets, password resets/account changes (after verification), proactively reporting device alerts, and scheduling onsite visits. Route new-contract/scoping and pricing to an account manager. Showcase live monitoring catching issues before the client notices.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your IT support today?",
    integrations: [
      { acronym: "RMM", name: "Remote Monitoring & Management" },
      { acronym: "PSA", name: "Professional Services Automation" },
      { acronym: "CRM", name: "Customer Relationship Management" },
    ],
    recommendedQuestions: [
      { title: "New Ticket", scenario: "Our whole office can't get to email this morning. Can you get someone on it now?" },
      { title: "Ticket Status", scenario: "What's the status on the ticket I opened yesterday about the slow server?" },
      { title: "Proactive Alert", scenario: "Did you catch anything unusual on our network overnight?" },
      { title: "User Onboarding", scenario: "We hired two people starting Monday. Can you set up their accounts and laptops?" },
      { title: "Password / Access", scenario: "I'm locked out of my account and have a deadline. Can you reset it?" },
      { title: "SLA / Response", scenario: "We have an outage — what's the guaranteed response time under our contract?" },
      { title: "Patching / Maintenance", scenario: "When is the next scheduled maintenance window?" },
      { title: "Security Concern", scenario: "One of our staff clicked a suspicious link. What do we do?" },
      { title: "Account Handoff", scenario: "We're opening a second location and need it set up. Who handles that?" },
    ],
  },
  {
    id: "junk-removal",
    displayName: "Junk Removal & Hauling",
    industry: "Junk Removal & Hauling",
    industryAddendum: "A junk removal/hauling company handling pickups and disposal for homes and businesses. Callers identified by account, address, or phone; jobs by booking number. Simulate records: scheduled pickups, crew/truck ETA, estimated load size/volume, past jobs, volume-based pricing tier, and donation/recycling handling. Workflows: booking pickups (single item to full cleanout), giving volume-based estimate ranges, scheduling same-/next-day service, crew ETA, and confirming what can/can't be hauled (hazmat exclusions). Route large commercial/recurring contracts to sales. Convey fast, same-day, no-hassle service.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your junk removal today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "RDS", name: "Routing & Dispatch System" },
    ],
    recommendedQuestions: [
      { title: "Same-Day Pickup", scenario: "I've got an old couch and a mattress to get rid of today. Can you grab them?" },
      { title: "Full Cleanout Estimate", scenario: "I'm clearing out my garage and basement. Roughly what would a full load cost?" },
      { title: "What You Take", scenario: "Can you haul away an old fridge and some paint cans?" },
      { title: "Crew ETA", scenario: "Your crew was booked for this morning — what's the ETA?" },
      { title: "Reschedule", scenario: "I need to move my pickup to tomorrow." },
      { title: "Donation / Recycling", scenario: "I'd rather donate the usable stuff. Do you handle that?" },
      { title: "Pricing Question", scenario: "How do you charge — by item or by truckload?" },
      { title: "Billing", scenario: "Can you explain the charge from my last pickup?" },
      { title: "Commercial Handoff", scenario: "My property management company needs regular hauling. Who sets that up?" },
    ],
  },
  {
    id: "landscaping",
    displayName: "Landscaping & Lawn Care Services",
    industry: "Landscaping & Lawn Care Services",
    industryAddendum: "A landscaping/lawn-care company providing recurring maintenance and project work. Callers identified by account, property address, or phone. Simulate records: service plan (mowing, fertilization, cleanup schedule), upcoming and past visits, crew ETA, property notes, seasonal treatment schedule, and billing/balance. Workflows: booking recurring service and one-time projects, rescheduling around weather, adjusting scope (aeration, mulch, trimming), crew ETA, seasonal treatment reminders, and giving package/visit ranges. Route large hardscape/design projects to an estimator. Convey reliable, proactive seasonal care.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your lawn or landscaping today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "BMS", name: "Billing & Scheduling" },
    ],
    recommendedQuestions: [
      { title: "New Service", scenario: "I'd like weekly mowing for my yard. What does that cost?" },
      { title: "Project Quote", scenario: "I want mulch added and the hedges trimmed. Can someone come look?" },
      { title: "Reschedule / Weather", scenario: "It's supposed to rain on my service day — will the crew still come?" },
      { title: "Seasonal Treatment", scenario: "Is it time for fall aeration and overseeding?" },
      { title: "Crew ETA", scenario: "What time is the crew coming today?" },
      { title: "Scope Adjustment", scenario: "Can you add the back flower beds to my regular service?" },
      { title: "Billing", scenario: "Can you explain this month's charges?" },
      { title: "Skip / Pause", scenario: "I'll be away — can we pause service for two weeks?" },
      { title: "Design Handoff", scenario: "I'm thinking about a full backyard redesign. Who do I talk to?" },
    ],
  },
  {
    id: "law-firms",
    displayName: "Law Firms & Legal Services",
    industry: "Law Firms & Legal Services",
    industryAddendum: "A law firm that handles client intake, case/matter management, scheduling, billing, and documents across practice areas. Callers identified by name and a matter/case number or client ID; appointments by a confirmation number. Simulate records: matter status and assigned attorney, upcoming consultations and court/filing dates, invoices and trust/retainer balances, and document/signature requests. Workflows: booking consultations, taking new-matter intake details, giving non-legal status updates on an existing matter, explaining an invoice or retainer balance, and routing to the responsible attorney or paralegal. Never give legal advice, predict outcomes, or interpret the law — for anything substantive, schedule a consultation or route to an attorney. Verify identity before discussing any matter and treat all case details as confidential.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your legal matter today?",
    integrations: [
      { acronym: "CMS", name: "Case Management System" },
      { acronym: "DMS", name: "Document Management System" },
      { acronym: "CRM", name: "Client Relationship Management" },
    ],
    recommendedQuestions: [
      { title: "New Client Intake", scenario: "I was in a car accident last week and think I need a lawyer. Can someone talk to me about my options?" },
      { title: "Consultation Booking", scenario: "I'd like a consultation about updating my will and estate plan." },
      { title: "Matter Status", scenario: "Any update on my case? It's been a few weeks since I heard from my attorney." },
      { title: "Court / Deadline Date", scenario: "When is my next court date, and what do I need to bring?" },
      { title: "Invoice / Retainer", scenario: "I got a bill but I thought my retainer covered this. Can you explain?" },
      { title: "Document / Signature", scenario: "My attorney sent documents to sign — did you get them back, and what's next?" },
      { title: "Practice-Area Scope", scenario: "I have a question about a tax issue. Does your firm handle that?" },
      { title: "Attorney Handoff", scenario: "I really need to speak with my attorney directly about something sensitive." },
      { title: "After-Hours Urgent", scenario: "I was just served with papers and the response is due Monday. What do I do?" },
    ],
  },
  {
    id: "locksmiths",
    displayName: "Locksmiths & Emergency Services",
    industry: "Locksmiths & Emergency Services",
    industryAddendum: "A locksmith/emergency-service company handling lockouts, rekeys, and security hardware for homes, businesses, and vehicles. Callers identified by name, location, or job number. Simulate records: active/past jobs, technician ETA and location, service-area coverage, pricing tiers (lockout, rekey, install), and warranty on hardware. Workflows: dispatching emergency lockouts with priority and live ETA, booking rekeys/installs, confirming service-call fee ranges, and verifying authorization to access (proof of residence/ownership) before service. For safety/danger situations, prioritize and advise. Route commercial master-key/access-control projects to a specialist.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your lock or security needs today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "RDS", name: "Routing & Dispatch System" },
    ],
    recommendedQuestions: [
      { title: "Emergency Lockout", scenario: "I'm locked out of my car with my kid inside. How fast can someone get here?" },
      { title: "Home Lockout", scenario: "I'm locked out of my house. Can you send someone now, and what's it cost?" },
      { title: "Rekey", scenario: "I just moved in and want all the locks rekeyed. Can you schedule that?" },
      { title: "Tech ETA", scenario: "Your locksmith is on the way — how far out are they?" },
      { title: "Service Area", scenario: "Do you cover my area? I'm out past the edge of town." },
      { title: "Pricing", scenario: "What's the typical cost for a car lockout this time of night?" },
      { title: "Lost Keys / Fob", scenario: "I lost my only car key. Can you make a new one on-site?" },
      { title: "Warranty", scenario: "The lock you installed is sticking. Is that covered?" },
      { title: "Commercial Handoff", scenario: "Our office needs a master-key system and access control. Who handles that?" },
    ],
  },
  {
    id: "moving-storage",
    displayName: "Moving & Storage Companies",
    industry: "Moving & Storage Companies",
    industryAddendum: "A moving and storage company handling local/long-distance moves and storage units. Callers identified by name, move/job number, or storage account. Simulate records: scheduled move date/time and crew, inventory/estimate, truck ETA, storage unit details and balance, insurance/valuation coverage, and quote status. Workflows: booking moves and in-home/virtual estimates, adjusting inventory and dates, crew ETA on move day, storage rentals and access, and giving move estimate ranges (final based on inventory). Route large commercial/long-distance custom quotes to a move coordinator. Convey organized, on-time, careful service.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your move or storage today?",
    integrations: [
      { acronym: "TMS", name: "Transportation Management System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "WMS", name: "Warehouse/Storage Management" },
    ],
    recommendedQuestions: [
      { title: "Move Quote", scenario: "I'm moving a two-bedroom across town next month. Roughly what does that cost?" },
      { title: "Book Estimate", scenario: "Can someone do a walkthrough for an accurate quote?" },
      { title: "Move-Day ETA", scenario: "What time is the crew arriving for my move tomorrow?" },
      { title: "Inventory Change", scenario: "I added a piano and some boxes since the estimate. Can you update it?" },
      { title: "Storage Rental", scenario: "I need to store furniture for a couple of months. What's available?" },
      { title: "Reschedule", scenario: "My closing got delayed — can we push the move back a week?" },
      { title: "Valuation / Insurance", scenario: "What coverage do I have if something gets damaged?" },
      { title: "Storage Access / Balance", scenario: "What's my storage balance, and when can I access my unit?" },
      { title: "Long-Distance Handoff", scenario: "I'm moving out of state. Who handles long-distance quotes?" },
    ],
  },
  {
    id: "pest-control",
    displayName: "Pest Control Companies",
    industry: "Pest Control Companies",
    industryAddendum: "A pest control company providing recurring treatments and one-time services. Callers identified by account, address, or phone; jobs by work-order number. Simulate records: service plan and treatment schedule, pest type/history, upcoming and past visits, technician ETA, warranty/re-treatment guarantee, and billing. Workflows: booking inspections and treatments, dispatching urgent infestations, scheduling recurring service, re-treatment under guarantee, prep instructions, and giving plan/treatment ranges. Route large commercial/termite-warranty contracts to a specialist. Convey proactive, guaranteed protection.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your pest control today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "BMS", name: "Billing & Scheduling" },
    ],
    recommendedQuestions: [
      { title: "Urgent Infestation", scenario: "I just found a wasp nest by my front door. Can you get someone out fast?" },
      { title: "New Plan", scenario: "I keep seeing ants. What does a regular treatment plan cost?" },
      { title: "Re-Treatment", scenario: "You treated for roaches last month and I'm still seeing them. Isn't that guaranteed?" },
      { title: "Schedule Visit", scenario: "Can you book my next quarterly treatment?" },
      { title: "Tech ETA", scenario: "What time is the technician coming today?" },
      { title: "Prep Instructions", scenario: "What do I need to do before the treatment?" },
      { title: "Safety", scenario: "Is the treatment safe for my pets and kids?" },
      { title: "Billing", scenario: "Can you explain my last invoice?" },
      { title: "Termite Handoff", scenario: "I think I have termites and need an inspection and warranty. Who handles that?" },
    ],
  },
  {
    id: "pet-grooming",
    displayName: "Pet Grooming, Boarding & Dog Daycares",
    industry: "Pet Grooming, Boarding & Dog Daycares",
    industryAddendum: "A pet grooming, boarding, and daycare business. Callers identified by owner name/phone or a pet profile ID. Simulate records: pet profile (breed, size, temperament, vaccination records), upcoming and past appointments/stays, grooming preferences and notes, package/membership and balance, and capacity/availability. Workflows: booking grooming, boarding, and daycare; checking vaccination requirements; recommending grooming services by breed; managing recurring daycare; and giving service pricing. Verify vaccination on file before boarding/daycare. Route medical/behavioral concerns to staff or recommend a vet. Convey attentive, loving care for each pet.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your pet today?",
    integrations: [
      { acronym: "PMS", name: "Pet Management System" },
      { acronym: "CRM", name: "Client Relationship Management" },
      { acronym: "BMS", name: "Booking & Billing" },
    ],
    recommendedQuestions: [
      { title: "Grooming Booking", scenario: "My golden retriever needs a full groom. What's available this week and the cost?" },
      { title: "Boarding Reservation", scenario: "We're traveling for a week. Can you board our two dogs, and what do you need from us?" },
      { title: "Vaccination Check", scenario: "Do you have my dog's shot records on file, or do I need to send them?" },
      { title: "Daycare Sign-Up", scenario: "I want to start bringing my puppy to daycare a few days a week. How does that work?" },
      { title: "Service Recommendation", scenario: "My cat's coat is matting. What grooming would you recommend?" },
      { title: "Reschedule", scenario: "Can I move my grooming appointment to Saturday?" },
      { title: "Package / Balance", scenario: "How many daycare days are left on my package?" },
      { title: "Special Needs", scenario: "My dog is anxious and on medication. Can you note that for boarding?" },
      { title: "Staff / Vet Routing", scenario: "My dog seems off after his last visit. Who can I talk to?" },
    ],
  },
  {
    id: "photography-video",
    displayName: "Photography & Videography Studios",
    industry: "Photography & Videography Studios",
    industryAddendum: "A photography/videography studio handling sessions, events, editing, and deliverables. Callers identified by name or a booking/project number. Simulate records: booked sessions/events (date, location, package), shoot status, editing/delivery timeline, gallery/proof status, contract/deposit/balance, and print/add-on orders. Workflows: booking sessions and consultations, package selection, status of editing and gallery delivery, ordering prints/albums, rescheduling, and deposit/balance questions. Route large weddings/commercial custom quotes to a studio coordinator. Convey a polished, creative, well-organized client experience.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your shoot or photos today?",
    integrations: [
      { acronym: "SMS", name: "Studio Management System" },
      { acronym: "CRM", name: "Client Relationship Management" },
      { acronym: "DAM", name: "Digital Asset Management" },
    ],
    recommendedQuestions: [
      { title: "New Booking", scenario: "I need family portraits before the holidays. What packages do you have and what's open?" },
      { title: "Gallery Status", scenario: "When will the photos from my session last week be ready to view?" },
      { title: "Editing Timeline", scenario: "How long until my wedding video is edited and delivered?" },
      { title: "Print / Album Order", scenario: "I'd like to order an album and some prints from my gallery." },
      { title: "Reschedule", scenario: "Can we move my session because of the weather forecast?" },
      { title: "Package Details", scenario: "What's included in the engagement package, and how many edited photos do I get?" },
      { title: "Deposit / Balance", scenario: "How much is left on my balance, and when is it due?" },
      { title: "Location / Logistics", scenario: "What time and where are we meeting for the shoot Saturday?" },
      { title: "Wedding / Commercial Handoff", scenario: "I'm planning a wedding and want full coverage. Who do I talk to?" },
    ],
  },
  {
    id: "plumbing",
    displayName: "Plumbing Services",
    industry: "Plumbing Services",
    industryAddendum: "A plumbing company serving residential and commercial customers. Callers identified by account, service address, or phone; jobs by work-order number. Simulate records: past work history, scheduled/upcoming appointments, technician ETA, warranty on prior work, fixture/equipment notes, and quote/estimate status. Workflows: booking diagnostics and installs, dispatching emergencies (burst pipe, no water, sewage backup) with priority and ETA, giving service-call/diagnostic fee ranges (not full project quotes), and offering a quick safe step (shutoff valve) for emergencies. Route large repipe/remodel estimates to an estimator. Convey fast, reliable, expert response.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your plumbing today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "ERP", name: "Enterprise Resource Planning" },
    ],
    recommendedQuestions: [
      { title: "Emergency Burst Pipe", scenario: "A pipe burst under my sink and water's everywhere. Can you get someone out now?" },
      { title: "No Hot Water", scenario: "I have no hot water this morning. Can you send a plumber today?" },
      { title: "Diagnostic Booking", scenario: "My toilet keeps running and a faucet drips. Can you schedule a visit?" },
      { title: "Water Heater Quote", scenario: "My water heater is old and leaking. Can someone assess a replacement?" },
      { title: "Tech ETA", scenario: "Your plumber was scheduled this morning — what's the ETA?" },
      { title: "Warranty", scenario: "You fixed my disposal last month and it's acting up again. Is it covered?" },
      { title: "Reschedule", scenario: "I need to move tomorrow's appointment." },
      { title: "Billing", scenario: "Can you explain the service-call fee on my invoice?" },
      { title: "Remodel Handoff", scenario: "We're redoing two bathrooms and need a full estimate. Who do I talk to?" },
    ],
  },
  {
    id: "pool-cleaning",
    displayName: "Pool Cleaning & Maintenance Companies",
    industry: "Pool Cleaning & Maintenance Companies",
    industryAddendum: "A pool cleaning/maintenance company providing recurring service and repairs. Callers identified by account, address, or phone. Simulate records: service plan and visit schedule, water chemistry/readings history, equipment (pump, filter, heater) status, upcoming and past visits, technician ETA, and billing. Workflows: booking recurring cleaning and one-time service, equipment repair/diagnostics, seasonal open/close, chemical balancing notes, technician ETA, and giving plan/service ranges. Route major equipment replacement/renovation quotes to a specialist. Convey proactive, worry-free pool care.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your pool today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "BMS", name: "Billing & Scheduling" },
    ],
    recommendedQuestions: [
      { title: "New Service", scenario: "I'd like weekly pool cleaning. What's included and what does it cost?" },
      { title: "Green Pool", scenario: "My pool turned green over the weekend. Can someone come treat it?" },
      { title: "Equipment Repair", scenario: "My pump is making a loud noise. Can you send a tech?" },
      { title: "Chemistry / Readings", scenario: "How did my water test out on the last visit?" },
      { title: "Tech ETA", scenario: "What day does my pool tech come this week?" },
      { title: "Seasonal Open/Close", scenario: "Can you schedule my pool closing for the season?" },
      { title: "Reschedule", scenario: "Can we skip this week and resume next week?" },
      { title: "Billing", scenario: "Can you explain my last invoice?" },
      { title: "Renovation Handoff", scenario: "I'm thinking about replacing my heater and resurfacing. Who quotes that?" },
    ],
  },
  {
    id: "printing",
    displayName: "Printing Services",
    industry: "Printing Services",
    industryAddendum: "A printing company handling print jobs (business cards, marketing materials, large-format banners, programs). Callers identified by name, company, or order/job number. Simulate records: order status and production stage, proof approval status, turnaround/delivery ETA, file/artwork status, reorder history, and quote status. Workflows: placing/reordering print jobs, checking production and proof status, rush turnaround options, file/artwork requirements, pickup/delivery, and giving quantity-based pricing ranges. Route large custom/commercial runs to an estimator. Convey fast, accurate, high-quality production. (This is marketing/print production — not copiers or managed print.)",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your print order today?",
    integrations: [
      { acronym: "MIS", name: "Print Management Information System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "OMS", name: "Order Management System" },
    ],
    recommendedQuestions: [
      { title: "New Order", scenario: "I need 500 business cards and some flyers. What's the cost and turnaround?" },
      { title: "Order Status", scenario: "Where's my order? I need the banners by Thursday." },
      { title: "Proof Approval", scenario: "Did you send the proof for my brochure yet? I want to approve it." },
      { title: "Rush Job", scenario: "I need 100 event programs by tomorrow afternoon. Can you do a rush?" },
      { title: "File / Artwork", scenario: "What format do you need my logo file in for printing?" },
      { title: "Reorder", scenario: "Can you reprint the same postcards from last quarter?" },
      { title: "Delivery / Pickup", scenario: "Is my order ready for pickup, or are you delivering it?" },
      { title: "Billing", scenario: "Can you explain the charge on my last invoice?" },
      { title: "Large Run Handoff", scenario: "We need a big quarterly catalog run. Who handles custom quotes?" },
    ],
  },
  {
    id: "tutoring-education",
    displayName: "Private Tutoring & Education Centers",
    industry: "Private Tutoring & Education Centers",
    industryAddendum: "A tutoring/education center managing student enrollment, sessions, and progress. Callers identified by parent/student name or an account/student ID. Simulate records: enrolled programs/subjects, session schedule and assigned tutor, progress/assessment notes, package/hours remaining, billing/autopay, and upcoming sessions. Workflows: enrollment and assessment booking, scheduling/rescheduling sessions, checking hours remaining and progress summaries, matching a tutor by subject, and giving package pricing. Route detailed curriculum and special-needs questions to a director. Convey personalized, results-focused learning support.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with tutoring or enrollment today?",
    integrations: [
      { acronym: "LMS", name: "Learning Management System" },
      { acronym: "CRM", name: "Student/Family Relationship Management" },
      { acronym: "SBS", name: "Scheduling & Billing System" },
    ],
    recommendedQuestions: [
      { title: "New Enrollment", scenario: "My son is struggling with algebra. Can you set up tutoring and an assessment?" },
      { title: "Tutor Match", scenario: "I need a tutor who specializes in SAT prep. Who do you have?" },
      { title: "Session Schedule", scenario: "Can you book two sessions a week for my daughter after school?" },
      { title: "Hours Remaining", scenario: "How many tutoring hours are left in our package?" },
      { title: "Progress Update", scenario: "How is my child doing — any progress notes from the last few sessions?" },
      { title: "Reschedule", scenario: "We need to move tomorrow's session to Thursday." },
      { title: "Billing", scenario: "Can you explain this month's charges?" },
      { title: "Program Options", scenario: "Do you offer group classes or only one-on-one?" },
      { title: "Director Handoff", scenario: "My child has a learning plan at school. Who can I talk to about accommodations?" },
    ],
  },
  {
    id: "property-management",
    displayName: "Property Management Companies",
    industry: "Property Management Companies",
    industryAddendum: "A property management company serving tenants and owners across residential/commercial units. Callers identified by name, unit/property address, or tenant/owner ID. Simulate records: lease details, rent balance/payment status, maintenance request status and ETA, unit availability, owner statements, and inspection/renewal schedule. Workflows: logging maintenance requests with priority and dispatch ETA, rent payment questions, lease renewal info, application/availability for prospective tenants, owner statement questions, and routing emergencies (flood, no heat) for priority dispatch. Route owner contract/pricing and new-management proposals to the team. Verify whether caller is tenant, owner, or prospect.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your property or unit today?",
    integrations: [
      { acronym: "PMS", name: "Property Management System" },
      { acronym: "CRM", name: "Tenant/Owner Relationship Management" },
      { acronym: "AMS", name: "Accounting Management System" },
    ],
    recommendedQuestions: [
      { title: "Maintenance Request", scenario: "My heat isn't working and it's freezing. Can you get someone out?" },
      { title: "Rent / Balance", scenario: "What's my current balance, and did my payment go through?" },
      { title: "Maintenance Status", scenario: "Any update on the leak I reported in my bathroom two days ago?" },
      { title: "Lease Renewal", scenario: "My lease is up soon — are you renewing it and at what rent?" },
      { title: "Availability (Prospect)", scenario: "Do you have any two-bedrooms available, and how do I apply?" },
      { title: "Emergency", scenario: "There's water coming through my ceiling right now. What do I do?" },
      { title: "Owner Statement", scenario: "I own a unit you manage — can you explain my last statement?" },
      { title: "Move-Out", scenario: "I'm moving out next month. What's the process for my deposit?" },
      { title: "New Management Handoff", scenario: "I have a few rentals and want you to manage them. Who do I talk to?" },
    ],
  },
  {
    id: "real-estate",
    displayName: "Real Estate Agencies",
    industry: "Real Estate Agencies",
    industryAddendum: "A real estate agency helping buyers and sellers. Callers identified by name/phone or a client/transaction ID. Simulate records: active listings and saved searches, showing schedule, offer/transaction status and key dates (inspection, appraisal, closing), agent assignment, and seller listing status/activity. Workflows: scheduling showings and consultations, sharing listing details and availability, status updates on an active transaction, listing/CMA requests, and routing offers and contract specifics to an agent. Never give legal/financial advice or quote what a home will sell for without an agent's CMA. Convey responsive, well-coordinated service.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with buying or selling today?",
    integrations: [
      { acronym: "MLS", name: "Multiple Listing Service" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "TMS", name: "Transaction Management System" },
    ],
    recommendedQuestions: [
      { title: "Buyer Inquiry", scenario: "I saw a listing on Maple Street I love. Can I schedule a showing this weekend?" },
      { title: "Listing Details", scenario: "Is the house on Oak Avenue still available, and what's the asking price?" },
      { title: "Transaction Status", scenario: "Where are we in my closing? Is the inspection scheduled yet?" },
      { title: "Seller / CMA", scenario: "I'm thinking about selling. Can someone tell me what my home is worth?" },
      { title: "Showing Schedule", scenario: "What showings do I have lined up this week?" },
      { title: "Offer Status", scenario: "Did the seller respond to the offer we submitted?" },
      { title: "Key Dates", scenario: "When's my appraisal and closing date again?" },
      { title: "Agent Match", scenario: "I'm relocating and need an agent who knows the area. Can you connect me?" },
      { title: "Contract Handoff", scenario: "I have questions about the contract terms. Can I talk to my agent?" },
    ],
  },
  {
    id: "roofing",
    displayName: "Roofing Contractors",
    industry: "Roofing Contractors",
    industryAddendum: "A roofing contractor handling repairs, replacements, and inspections for residential/commercial properties. Callers identified by account, property address, or phone; jobs by work-order/project number. Simulate records: inspection and project status, scheduled work and crew ETA, materials/order status, warranty on prior work, insurance-claim coordination, and estimate status. Workflows: booking inspections and repairs, dispatching emergency leaks with priority and ETA, project status updates, insurance-claim assistance, warranty service, and giving inspection/repair ranges (full replacement requires inspection). Route large replacement/commercial estimates to an estimator. Convey dependable, weatherproof protection.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your roof today?",
    integrations: [
      { acronym: "FSM", name: "Field Service Management" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "ERP", name: "Enterprise Resource Planning" },
    ],
    recommendedQuestions: [
      { title: "Emergency Leak", scenario: "My roof is leaking into my living room during this storm. Can someone come now?" },
      { title: "Inspection Booking", scenario: "I want my roof inspected before winter. Can you schedule that?" },
      { title: "Replacement Estimate", scenario: "My roof is 25 years old. Can someone assess a full replacement?" },
      { title: "Project Status", scenario: "Where does my roof replacement stand — are materials in?" },
      { title: "Insurance Claim", scenario: "I had storm damage. Can you help with my insurance claim?" },
      { title: "Crew ETA", scenario: "What day is the crew starting my repair?" },
      { title: "Warranty", scenario: "You replaced my roof two years ago and I see a drip. Is that covered?" },
      { title: "Billing", scenario: "Can you explain the charges on my estimate?" },
      { title: "Commercial Handoff", scenario: "We need a flat roof replaced on our building. Who handles commercial?" },
    ],
  },
  {
    id: "self-storage",
    displayName: "Self-Storage Facilities",
    industry: "Self-Storage Facilities",
    industryAddendum: "A self-storage facility renting units and managing access. Callers identified by name, unit number, or account. Simulate records: unit size/type and rate, lease and payment/autopay status, gate-access status, availability by size, insurance/protection plan, and move-in/out schedule. Workflows: checking availability and reserving units, explaining sizes and pricing, payment/autopay questions, gate-access issues, move-in/out scheduling, and protection-plan info. Route business/multi-unit and long-term discounts to the manager. Convey easy, secure, flexible storage.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your storage unit today?",
    integrations: [
      { acronym: "FMS", name: "Facility Management System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "BAS", name: "Billing & Access System" },
    ],
    recommendedQuestions: [
      { title: "Unit Availability", scenario: "I need a 10-by-10 unit starting this weekend. What do you have and what's the rate?" },
      { title: "Size Help", scenario: "I'm storing a one-bedroom apartment. What size unit do I need?" },
      { title: "Payment / Autopay", scenario: "What's my balance, and is autopay turned on?" },
      { title: "Gate Access", scenario: "My gate code isn't working. Can you fix my access?" },
      { title: "Reserve / Move-In", scenario: "Can I reserve a climate-controlled unit and move in Saturday?" },
      { title: "Move-Out", scenario: "I want to move out at the end of the month. What's the process?" },
      { title: "Protection Plan", scenario: "Do I have insurance on my unit, and what does it cover?" },
      { title: "Rate Change", scenario: "My rate went up — can you explain why?" },
      { title: "Business Handoff", scenario: "My business needs several units long-term. Who can discuss a deal?" },
    ],
  },
  {
    id: "signage-display",
    displayName: "Signage & Display Companies",
    industry: "Signage & Display Companies",
    industryAddendum: "A signage and display company designing, fabricating, and installing signs. Callers identified by name, company, or project/order number. Simulate records: project status and production stage, proof/design approval, permit status (exterior signs), install schedule and crew ETA, materials/order status, and quote status. Workflows: starting new sign projects, design/proof approval status, production and install timelines, permit coordination, reorders, and giving project estimate ranges. Route large custom/commercial fabrication to an estimator. Convey high-impact, professional results delivered on schedule.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your signage project today?",
    integrations: [
      { acronym: "MIS", name: "Manufacturing Information System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "OMS", name: "Order & Project Management System" },
    ],
    recommendedQuestions: [
      { title: "New Project", scenario: "We're opening a storefront and need an exterior sign. Where do we start and what's the cost?" },
      { title: "Project Status", scenario: "Where's my sign project — is it in production yet?" },
      { title: "Proof Approval", scenario: "Did you send the design proof? I'd like to approve it to stay on schedule." },
      { title: "Permit Status", scenario: "Has the permit for our building sign been approved?" },
      { title: "Install Schedule", scenario: "When is the crew installing our sign?" },
      { title: "Rush / Event", scenario: "We have a trade show next week and need banners and a display fast. Possible?" },
      { title: "Reorder", scenario: "Can you remake the same yard signs we ordered last time?" },
      { title: "Billing", scenario: "Can you explain the charges on my project estimate?" },
      { title: "Custom Handoff", scenario: "We need signage for 20 locations. Who handles large rollouts?" },
    ],
  },
  {
    id: "solar",
    displayName: "Solar Energy Installers",
    industry: "Solar Energy Installers",
    industryAddendum: "A solar energy company handling consultations, design, installation, and service. Callers identified by name, address, or project number. Simulate records: project stage (consultation, design, permitting, install, inspection, activation), system size and estimated production, permit/utility-interconnection status, install schedule and crew ETA, monitoring/performance, and warranty. Workflows: booking consultations and site assessments, project status updates, monitoring/production questions, warranty/service, and routing detailed pricing/financing and custom design to a solar advisor. Never invent specific pricing, incentives, or guaranteed savings figures — route those to an advisor. Convey clean-energy expertise and smooth project delivery.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your solar project today?",
    integrations: [
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "PVM", name: "PV Project & Design Management" },
      { acronym: "ERP", name: "Enterprise Resource Planning" },
    ],
    recommendedQuestions: [
      { title: "New Consultation", scenario: "I'm interested in going solar. Can someone assess my home and savings?" },
      { title: "Project Status", scenario: "Where's my installation — are we through permitting yet?" },
      { title: "Production / Monitoring", scenario: "Is my system producing what it should? My bill seems high." },
      { title: "Install Schedule", scenario: "When is the crew coming to install my panels?" },
      { title: "Interconnection", scenario: "Has the utility approved my system to turn on yet?" },
      { title: "Warranty / Service", scenario: "One of my panels seems to be underperforming. Is that covered?" },
      { title: "Incentives", scenario: "What tax credits or incentives can I get?" },
      { title: "Billing / Financing", scenario: "Can you explain my financing payment?" },
      { title: "Advisor Handoff", scenario: "I want to add a battery and discuss options. Who do I talk to?" },
    ],
  },
  {
    id: "staffing-recruitment",
    displayName: "Staffing & Recruitment Agencies",
    industry: "Staffing & Recruitment Agencies",
    industryAddendum: "A staffing/recruitment agency serving job seekers and employer clients. Callers identified by name (candidate) or company/contact (client), plus a candidate or job-order ID. Simulate records: candidate profile and application status, open job orders and placements, interview schedule, onboarding/paperwork status, timesheet/payroll (placed workers), and client requisitions. Workflows: candidate application status and interview scheduling, matching candidates to roles, client job-order intake and submittal status, onboarding/timesheet questions, and routing contract/rate negotiations to an account manager. Verify whether caller is a candidate or client. Convey fast, high-quality matching.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your job search or staffing needs today?",
    integrations: [
      { acronym: "ATS", name: "Applicant Tracking System" },
      { acronym: "CRM", name: "Client Relationship Management" },
      { acronym: "HRIS", name: "HR Information System" },
    ],
    recommendedQuestions: [
      { title: "Candidate Status", scenario: "I applied for the warehouse role last week. Where does my application stand?" },
      { title: "Interview Schedule", scenario: "Can you set up my interview for the admin position?" },
      { title: "Job Match", scenario: "I'm looking for full-time accounting work. What do you have open?" },
      { title: "Client Job Order", scenario: "We need three temp workers next week. Can you help us fill that?" },
      { title: "Submittal Status", scenario: "Have you sent over any candidates for our open role yet?" },
      { title: "Onboarding / Paperwork", scenario: "What do I still need to complete before I start Monday?" },
      { title: "Timesheet / Payroll", scenario: "I'm placed through you — how do I submit my hours this week?" },
      { title: "Placement Follow-Up", scenario: "How's the candidate we hired working out — anything I need to do?" },
      { title: "Account Handoff", scenario: "We want an ongoing staffing contract. Who do I talk to?" },
    ],
  },
  {
    id: "travel-tours",
    displayName: "Travel & Tour Operators",
    industry: "Travel & Tour Operators",
    industryAddendum: "A travel/tour operator handling trip bookings, itineraries, and support. Callers identified by name, booking/reservation number, or loyalty ID. Simulate records: booked trips and itinerary details, payment/balance and due dates, availability for tours/packages, change/cancellation policies, travel documents/requirements, and loyalty status. Workflows: booking and modifying trips, itinerary details and timing, payment/balance, availability and recommendations, cancellation/change handling, and travel-requirement reminders. Route complex custom/group itineraries and special pricing to a travel advisor. Convey seamless, well-planned, exciting travel experiences.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your trip today?",
    integrations: [
      { acronym: "GDS", name: "Global Distribution System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "BMS", name: "Booking Management System" },
    ],
    recommendedQuestions: [
      { title: "New Booking", scenario: "I want to book a week in Costa Rica next spring. What packages do you have?" },
      { title: "Itinerary Details", scenario: "Can you confirm the times and pickup for my tour on day three?" },
      { title: "Balance / Payment", scenario: "How much is left on my trip, and when is the final payment due?" },
      { title: "Change / Cancel", scenario: "I need to change my return flight date. Is that possible?" },
      { title: "Availability", scenario: "Do you have any spots left on the August wine tour?" },
      { title: "Travel Docs", scenario: "Do I need a visa or anything special for this destination?" },
      { title: "Recommendations", scenario: "We want a family-friendly trip in July. What would you suggest?" },
      { title: "Loyalty", scenario: "How many points do I have, and can I use them toward this trip?" },
      { title: "Custom / Group Handoff", scenario: "I'm planning a group trip for 12. Who builds custom itineraries?" },
    ],
  },
  {
    id: "veterinary",
    displayName: "Veterinary Clinics",
    industry: "Veterinary Clinics",
    industryAddendum: "A veterinary clinic managing pet patients, appointments, and care. Callers identified by owner name/phone and a pet patient ID. Simulate records: pet profile and history, appointment schedule, vaccination/medication due dates, refill requests (routed to clinical staff), lab/result status, account balance, and recall reminders. Workflows: scheduling/rescheduling visits, vaccination/wellness reminders, refill requests routed to clinical staff, explaining bills, and routing medical questions to a vet/tech. Never give medical advice or a diagnosis — for symptoms, recommend a visit or route to clinical staff; for emergencies, direct to the emergency vet line. Verify the caller is an authorized owner before sharing details.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your pet's care today?",
    integrations: [
      { acronym: "PIMS", name: "Patient Information Management System" },
      { acronym: "CRM", name: "Client Relationship Management" },
      { acronym: "RCM", name: "Revenue Cycle Management" },
    ],
    recommendedQuestions: [
      { title: "Sick Visit", scenario: "My dog has been vomiting since last night. Can he be seen today?" },
      { title: "Wellness / Vaccines", scenario: "Is my cat due for any vaccines, and can I book her annual checkup?" },
      { title: "Prescription Refill", scenario: "I need a refill on my dog's heartworm medication." },
      { title: "Reschedule", scenario: "Can I move my pet's dental appointment to next week?" },
      { title: "Lab Results", scenario: "Are my dog's bloodwork results back from last week?" },
      { title: "Billing", scenario: "Can you explain the charges from my last visit?" },
      { title: "New Patient", scenario: "I just adopted a puppy. Can I set up his first vet visit?" },
      { title: "Emergency Routing", scenario: "My cat got into something toxic — what do I do right now?" },
      { title: "Records / Boarding", scenario: "Can you send my pet's vaccine records to a boarding facility?" },
    ],
  },
  {
    id: "waste-management",
    displayName: "Waste Management Companies",
    industry: "Waste Management Companies",
    industryAddendum: "A waste management/collection company serving residential and commercial customers. Callers identified by account, service address, or phone. Simulate records: service plan and pickup schedule (trash, recycling, yard waste, bulk), missed-pickup status, container/dumpster size and delivery, route timing, and billing/balance. Workflows: scheduling service and bulk pickups, reporting missed pickups with a make-up time, adjusting container size/frequency, holiday-schedule info, roll-off/dumpster rentals, and giving plan/rate ranges. Route large commercial/construction roll-off contracts to sales. Convey reliable, on-schedule, hassle-free service.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you with your waste or recycling service today?",
    integrations: [
      { acronym: "RDS", name: "Routing & Dispatch System" },
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "BMS", name: "Billing & Scheduling" },
    ],
    recommendedQuestions: [
      { title: "Missed Pickup", scenario: "My trash wasn't collected this morning. Can you send someone back?" },
      { title: "New Service", scenario: "I just moved in and need to set up trash and recycling. What does it cost?" },
      { title: "Bulk Pickup", scenario: "I have an old couch and some boxes. How do I schedule a bulk pickup?" },
      { title: "Schedule / Holiday", scenario: "Is pickup delayed this week because of the holiday?" },
      { title: "Container Change", scenario: "Can I get a bigger recycling bin, or an extra one?" },
      { title: "Dumpster Rental", scenario: "I'm doing a reno and need a roll-off dumpster for two weeks." },
      { title: "Billing", scenario: "Can you explain the increase on my latest bill?" },
      { title: "Pause / Vacation", scenario: "I'll be away for a month — can I pause service?" },
      { title: "Commercial Handoff", scenario: "My business needs regular commercial pickup. Who sets that up?" },
    ],
  },
  {
    id: "general-business",
    displayName: "General Business",
    industry: "general",
    industryAddendum: "A general small-to-midsize business assistant for inbound calls at a company that isn't in a specialized vertical. Identify callers by name, phone, or email, and look up or create a basic contact record. Simulate: business hours, location and directions, the services or products the business offers, contact records and recent interaction history, calendar availability, meetings and appointments, messages, and follow-up tasks. Workflows: answer common questions (hours, location, what the business does, how to get started); capture the caller's details and log them to the CRM; take a message and route it to the right person; and manage meetings on the calendar — check availability, offer a few specific open time slots, book the meeting or appointment, confirm the date and time, and send a calendar invite plus an email confirmation. Also reschedule or cancel an existing meeting on request. Keep specifics plausible and modest — do not invent specialized industry systems or equipment. Never quote firm pricing; route pricing, quotes, and detailed sales questions to the right team member.",
    greeting: "Thank you for calling, this is Phoebe your AI Assistant on a recorded line, how can I help you today?",
    integrations: [
      { acronym: "CRM", name: "Customer Relationship Management" },
      { acronym: "EMAIL", name: "Email & Messaging" },
      { acronym: "CAL", name: "Calendar & Scheduling" },
    ],
    recommendedQuestions: [
      { title: "Business Hours", scenario: "What are your hours today, and are you open this weekend?" },
      { title: "Location & Directions", scenario: "Where are you located, and is there parking nearby?" },
      { title: "What You Do", scenario: "Can you tell me a bit about what your business does?" },
      { title: "Book a Meeting", scenario: "I'd like to book a 30-minute meeting this week. What times do you have open?" },
      { title: "Reschedule Meeting", scenario: "I need to move my Thursday meeting to next week. Can you do that?" },
      { title: "Leave a Message", scenario: "Can you take a message and have someone get back to me?" },
      { title: "Email Follow-Up", scenario: "Can you email me the details and a calendar invite for our meeting?" },
      { title: "Update My Info", scenario: "I have a new phone number and email — can you update my contact info?" },
      { title: "Pricing / Sales", scenario: "How much do your services cost, and who can I talk to about a quote?" },
    ],
  },
];

export const DEFAULT_INDUSTRY_ID = "document-solutions";

export function getIndustry(id: string | null | undefined): IndustryConfig {
  const fallback = INDUSTRIES.find((i) => i.id === DEFAULT_INDUSTRY_ID) ?? INDUSTRIES[0];
  if (!id) return fallback;
  return INDUSTRIES.find((i) => i.id === id) ?? fallback;
}
