CREATE SCHEMA IF NOT EXISTS internal;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE OR REPLACE FUNCTION public.enqueue_email(queue_name TEXT, payload JSONB) RETURNS BIGINT LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.read_email_batch(queue_name TEXT, batch_size INT, vt INT) RETURNS TABLE(msg_id BIGINT, read_ct INT, message JSONB) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.delete_email(queue_name TEXT, message_id BIGINT) RETURNS BOOLEAN LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.move_to_dlq(source_queue TEXT, dlq_name TEXT, message_id BIGINT, payload JSONB) RETURNS BIGINT LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.get_org_billing_card(_org_id uuid) RETURNS TABLE(card_brand text, card_last4 text, card_exp_month integer, card_exp_year integer, stripe_payment_method_id text) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.get_public_sandbox(p_slug text) RETURNS TABLE(slug text, company_name text, vapi_assistant_id text, vapi_public_key text, is_active boolean) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.handle_new_user_role() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.portal_handle_new_user() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.bootstrap_org_for_new_user() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.audit_profile_sensitive() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.audit_sensitive_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.data_retention_sweep_report() RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.dsar_redact_subject(_customer_id uuid, _email text DEFAULT NULL, _phone text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.record_call_usage(_organization_id uuid, _vapi_call_id text, _seconds int, _metadata jsonb DEFAULT '{}'::jsonb) RETURNS uuid LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.consume_ai_tokens(customer_id uuid, tokens bigint) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION public.admin_user_activity_summary(_caller uuid DEFAULT auth.uid()) RETURNS TABLE( user_id uuid, email text, display_name text, role app_role, signed_up_at timestamptz, last_login_at timestamptz, login_success_count bigint, login_failed_count bigint, total_session_seconds bigint, sandbox_call_count bigint, sandbox_total_seconds bigint ) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.log_audit_event(action text, entity_type text, entity_id text, metadata jsonb DEFAULT '{}'::jsonb, actor_id uuid DEFAULT auth.uid()) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION public.log_ai_action(customer_id uuid, action text, model text, risk_level text, rationale text, resource_id uuid, actor_user_id uuid, agent_id text, call_id text, model_version text, metadata jsonb, decision text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION public.dsar_export_subject(_customer_id uuid, _email text DEFAULT NULL, _phone text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.record_consent_change(customer_id uuid, channel public.consent_channel, status public.consent_status, contact_email text, contact_phone text, source public.consent_source, evidence_url text, notes text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION public.tenant_compliance_summary(_customer_id uuid) RETURNS TABLE(regulation_code text, regulation_name text, legal_agreement_status text, annex_generated boolean, controls_mapped integer) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.tenant_compliance_evidence_status(_customer_id uuid) RETURNS TABLE(agreement_type text, status text, signed_at timestamptz, expires_at timestamptz, is_complete boolean) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.list_integration_statuses(_customer_id uuid) RETURNS TABLE(integration_id text, status text, last_tested_at timestamptz, last_test_outcome text, last_test_error text, field_hints jsonb, updated_at timestamptz) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.set_account_mode(_mode text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION public.redeem_live_access_code(_code text) RETURNS TABLE(customer_id uuid, display_name text) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.get_my_live_account() RETURNS TABLE(customer_id uuid, display_name text, is_active boolean) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.has_org_role(_org_id uuid, _roles public.org_member_role[], _user_id uuid DEFAULT auth.uid()) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.is_org_member(_org_id uuid, _user_id uuid DEFAULT auth.uid()) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.is_internal_operator(_user_id uuid DEFAULT auth.uid()) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.portal_is_org_member(_user_id uuid, _org_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.portal_has_org_role(_user_id uuid, _org_id uuid, _role portal_membership_role) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.portal_can_view_location(_user_id uuid, _location_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.tenant_of(_user_id uuid) RETURNS uuid LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.current_org_id() RETURNS uuid LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.check_consent(customer_id uuid, channel public.consent_channel, contact_email text, contact_phone text) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.outbound_allowed(customer_id uuid, channel public.consent_channel) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.is_outbound_paused(customer_id uuid, channel public.consent_channel) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION public.is_email(_email text) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END; $$;
CREATE OR REPLACE FUNCTION internal.get_my_live_account_impl() RETURNS TABLE(customer_id uuid, display_name text, is_active boolean) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION internal.get_public_sandbox_impl(p_slug text) RETURNS TABLE(slug text, company_name text, vapi_assistant_id text, vapi_public_key text, is_active boolean) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION internal.list_integration_statuses_impl(_customer_id uuid) RETURNS TABLE(integration_id text, status text, last_tested_at timestamptz, last_test_outcome text, last_test_error text, field_hints jsonb, updated_at timestamptz) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION internal.redeem_live_access_code_impl(_code text) RETURNS TABLE(customer_id uuid, display_name text) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION internal.set_account_mode_impl(_mode text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION internal.tenant_compliance_evidence_status_impl(_customer_id uuid) RETURNS TABLE(agreement_type text, status text, signed_at timestamptz, expires_at timestamptz, is_complete boolean) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION internal.tenant_compliance_summary_impl(_customer_id uuid) RETURNS TABLE(regulation_code text, regulation_name text, legal_agreement_status text, annex_generated boolean, controls_mapped integer) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.set_active_tools(_customer_id uuid, _retell_agent_id text, _tools jsonb) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION public.match_knowledge(_customer_id uuid, _query_embedding vector(1536), _k int DEFAULT 5) RETURNS TABLE (id uuid, text_chunk text, source_url text, similarity float) LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE OR REPLACE FUNCTION public.email_queue_dispatch() RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION public.email_queue_wake() RETURNS void LANGUAGE plpgsql AS $$ BEGIN END; $$;
